defmodule Batcher.Repo.Migrations.InitialSetupWithEndpoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :rabbitmq_queue, :text
      add :webhook_url, :text
      add :delivery_type, :text, null: false
      add :error_msg, :text
      add :state, :text, null: false
      add :tag, :text
      add :request_payload, :map, null: false
      add :custom_id, :text, null: false
      add :model, :text, null: false
      add :endpoint, :text, null: false

      add :batch_id,
          references(:batches,
            column: :id,
            name: "prompts_batch_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          ),
          null: false

      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:prompt_transitions, primary_key: false) do
      add :prompt_id,
          references(:prompts,
            column: :id,
            name: "prompt_transitions_prompt_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          ),
          null: false

      add :transitioned_at, :utc_datetime_usec, null: false
      add :to, :text, null: false
      add :from, :text
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:batches, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :error_msg, :text
      add :model, :text, null: false
      add :endpoint, :text, null: false
      add :provider, :text, null: false
      add :provider_batch_id, :text
      add :state, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create index(:prompts, ["custom_id"], unique: true)

    create table(:batch_transitions, primary_key: false) do
      add :batch_id,
          references(:batches,
            column: :id,
            name: "batch_transitions_batch_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          ),
          null: false

      add :transitioned_at, :utc_datetime_usec, null: false
      add :to, :text, null: false
      add :from, :text
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:batch_transitions, "batch_transitions_batch_id_fkey")

    drop table(:batch_transitions)

    drop_if_exists index(:prompts, ["custom_id"], name: "prompts_custom_id_index")

    drop table(:batches)

    drop constraint(:prompt_transitions, "prompt_transitions_prompt_id_fkey")

    drop table(:prompt_transitions)

    drop constraint(:prompts, "prompts_batch_id_fkey")

    drop table(:prompts)
  end
end
