defmodule Batcher.Repo.Migrations.AddResponsePayloadToRequest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:requests) do
      add :response_payload, :map
    end
  end

  def down do
    alter table(:requests) do
      remove :response_payload
    end
  end
end