defmodule Batcher.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:requests, primary_key: false) do
      add :batch_id,
          references(:batches,
            column: :id,
            name: "requests_batch_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :error_msg, :text
      add :rabbitmq_queue, :text
      add :rabbitmq_exchange, :text
      add :webhook_url, :text
      add :delivery_type, :text, null: false
      add :state, :text, null: false
      add :request_payload_size, :bigint, null: false
      add :request_payload, :text, null: false
      add :model, :text, null: false
      add :url, :text, null: false
      add :custom_id, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:request_transitions, primary_key: false) do
      add :request_id,
          references(:requests,
            column: :id,
            name: "request_transitions_request_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          ),
          null: false

      add :transitioned_at, :utc_datetime_usec, null: false
      add :to, :text, null: false
      add :from, :text
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:batches, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :output_tokens, :bigint
      add :reasoning_tokens, :bigint
      add :cached_tokens, :bigint
      add :input_tokens, :bigint
      add :error_msg, :text
      add :model, :text, null: false
      add :url, :text, null: false
      add :openai_batch_id, :text
      add :openai_output_file_id, :text
      add :openai_input_file_id, :text
      add :state, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create index(:requests, ["custom_id", "batch_id"], unique: true)

    create table(:batch_transitions, primary_key: false) do
      add :batch_id,
          references(:batches,
            column: :id,
            name: "batch_transitions_batch_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          ),
          null: false

      add :transitioned_at, :utc_datetime_usec, null: false
      add :to, :text, null: false
      add :from, :text
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:batch_transitions, "batch_transitions_batch_id_fkey")

    drop table(:batch_transitions)

    drop_if_exists index(:requests, ["custom_id", "batch_id"],
                     name: "requests_custom_id_batch_id_index"
                   )

    drop table(:batches)

    drop constraint(:request_transitions, "request_transitions_request_id_fkey")

    drop table(:request_transitions)

    drop constraint(:requests, "requests_batch_id_fkey")

    drop table(:requests)
  end
end