defmodule Batcher.Repo.Migrations.AddRequeustPayloadSizeToPrompt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:prompts) do
      add :request_payload_size, :bigint, null: false
    end
  end

  def down do
    alter table(:prompts) do
      remove :request_payload_size
    end
  end
end