defmodule Batcher.Repo.Migrations.AddOpenaiStatusLastCheckedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:batches) do
      add :openai_status_last_checked_at, :utc_datetime
    end
  end

  def down do
    alter table(:batches) do
      remove :openai_status_last_checked_at
    end
  end
end