defmodule Batcher.Repo.Migrations.RemoveRetryDeliveryColumnsAndAttemptNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    SELECT 1;
    """)

    drop_if_exists index(:request_delivery_attempts, [:request_id, :attempt_number])

    alter table(:request_delivery_attempts) do
      remove_if_exists :attempt_number
    end
  end

  def down do
    alter table(:request_delivery_attempts) do
      add :attempt_number, :bigint, null: false
    end

    create index(:request_delivery_attempts, [:request_id, :attempt_number], unique: true)

    execute("""
    UPDATE batches
    SET
      request_count = (
        SELECT COUNT(*)
        FROM requests
        WHERE requests.batch_id = batches.id
      ),
      estimated_input_tokens_total = COALESCE((
        SELECT SUM(estimated_input_tokens)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0),
      estimated_request_input_tokens_total = COALESCE((
        SELECT SUM(estimated_request_input_tokens)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0),
      size_bytes = COALESCE((
        SELECT SUM(request_payload_size)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0)
    """)
  end
end
