defmodule Batcher.Repo.Migrations.AddSettingsForModelTokenOverrides do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :model_token_overrides, :map, null: false, default: %{}
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:settings, [:name], name: "settings_unique_settings_name_index")
  end

  def down do
    drop_if_exists unique_index(:settings, [:name], name: "settings_unique_settings_name_index")

    drop table(:settings)
  end
end
