defmodule Batcher.Repo.Migrations.CleanupLegacyRequestDeliveryCounterTrigger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DROP TRIGGER IF EXISTS request_delivery_attempts_after_insert_update_request_attempt_count ON request_delivery_attempts;
    """)

    execute("""
    DROP FUNCTION IF EXISTS request_delivery_attempts_after_insert_update_request_attempt_count_fn();
    """)
  end

  def down do
    execute("""
    SELECT 1;
    """)

    execute("""
    SELECT 1;
    """)
  end
end
