defmodule Batcher.Repo.Migrations.PaginationIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:requests, [:batch_id, :created_at])

    drop_if_exists index(:requests, [:created_at])

    create index(:requests, [:batch_id, :created_at, :id],
             name: "requests_batch_pagination_created_at_id_index"
           )

    create index(:requests, [:created_at, :id], name: "requests_pagination_created_at_id_index")

    create index(:batches, [:created_at, :id], name: "batches_pagination_created_at_id_index")
  end

  def down do
    drop_if_exists index(:batches, [:created_at, :id],
                     name: "batches_pagination_created_at_id_index"
                   )

    drop_if_exists index(:requests, [:created_at, :id],
                     name: "requests_pagination_created_at_id_index"
                   )

    drop_if_exists index(:requests, [:batch_id, :created_at, :id],
                     name: "requests_batch_pagination_created_at_id_index"
                   )

    create index(:requests, [:created_at])

    create index(:requests, [:batch_id, :created_at])
  end
end
