defmodule Batcher.Repo.Migrations.KeysetPaginationAndTransitionIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:batch_transitions, [:batch_id, :to, :transitioned_at],
             name: "batch_transitions_processing_since_index"
           )
  end

  def down do
    drop_if_exists index(:batch_transitions, [:batch_id, :to, :transitioned_at],
                     name: "batch_transitions_processing_since_index"
                   )
  end
end
