defmodule Batcher.Repo.Migrations.AddIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:requests, ["batch_id"])

    create index(:request_delivery_attempts, ["request_id"])

    create index(:batch_transitions, ["batch_id"])
  end

  def down do
    drop_if_exists index(:batch_transitions, ["batch_id"],
                     name: "batch_transitions_batch_id_index"
                   )

    drop_if_exists index(:request_delivery_attempts, ["request_id"],
                     name: "request_delivery_attempts_request_id_index"
                   )

    drop_if_exists index(:requests, ["batch_id"], name: "requests_batch_id_index")
  end
end