defmodule Batcher.Repo.Migrations.SqliteThroughputUpgrade do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:batches) do
      add :request_count, :bigint, null: false, default: 0
      add :size_bytes, :bigint, null: false, default: 0
    end

    create index(:batches, ["state", "model", "url"], name: "batches_state_model_url_index")

    execute("""
    UPDATE batches
    SET
      request_count = (
        SELECT COUNT(*)
        FROM requests
        WHERE requests.batch_id = batches.id
      ),
      size_bytes = COALESCE((
        SELECT SUM(request_payload_size)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0)
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_insert_update_batch_counters
    AFTER INSERT ON requests
    BEGIN
      UPDATE batches
      SET
        request_count = request_count + 1,
        size_bytes = size_bytes + COALESCE(NEW.request_payload_size, 0)
      WHERE id = NEW.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_delete_update_batch_counters
    AFTER DELETE ON requests
    BEGIN
      UPDATE batches
      SET
        request_count = request_count - 1,
        size_bytes = size_bytes - COALESCE(OLD.request_payload_size, 0)
      WHERE id = OLD.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_update_same_batch_update_counters
    AFTER UPDATE OF request_payload_size ON requests
    WHEN OLD.batch_id = NEW.batch_id
    BEGIN
      UPDATE batches
      SET size_bytes = size_bytes + (COALESCE(NEW.request_payload_size, 0) - COALESCE(OLD.request_payload_size, 0))
      WHERE id = NEW.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_update_move_batch_update_counters
    AFTER UPDATE OF batch_id, request_payload_size ON requests
    WHEN OLD.batch_id != NEW.batch_id
    BEGIN
      UPDATE batches
      SET
        request_count = request_count - 1,
        size_bytes = size_bytes - COALESCE(OLD.request_payload_size, 0)
      WHERE id = OLD.batch_id;

      UPDATE batches
      SET
        request_count = request_count + 1,
        size_bytes = size_bytes + COALESCE(NEW.request_payload_size, 0)
      WHERE id = NEW.batch_id;
    END;
    """)
  end

  def down do
    execute("""
    DROP TRIGGER IF EXISTS requests_after_update_move_batch_update_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_update_same_batch_update_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_delete_update_batch_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_insert_update_batch_counters;
    """)

    execute("""
    SELECT 1;
    """)

    drop_if_exists index(:batches, ["state", "model", "url"],
                     name: "batches_state_model_url_index"
                   )

    alter table(:batches) do
      remove :size_bytes
      remove :request_count
    end
  end
end
