defmodule Batcher.Repo.Migrations.RequestTokenEstimateMetrics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    SELECT 1;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_insert_update_batch_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_delete_update_batch_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_update_same_batch_update_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_update_move_batch_update_counters;
    """)

    alter table(:requests) do
      add :estimated_request_input_tokens, :bigint, null: false, default: 0
    end

    alter table(:batches) do
      add :estimated_request_input_tokens_total, :bigint, null: false, default: 0
    end

    execute("""
    UPDATE batches
    SET
      request_count = (
        SELECT COUNT(*)
        FROM requests
        WHERE requests.batch_id = batches.id
      ),
      estimated_input_tokens_total = COALESCE((
        SELECT SUM(estimated_input_tokens)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0),
      estimated_request_input_tokens_total = COALESCE((
        SELECT SUM(estimated_request_input_tokens)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0),
      size_bytes = COALESCE((
        SELECT SUM(request_payload_size)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0)
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_insert_update_batch_counters
    AFTER INSERT ON requests
    BEGIN
      UPDATE batches
      SET
        request_count = request_count + 1,
        size_bytes = size_bytes + COALESCE(NEW.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total + COALESCE(NEW.estimated_input_tokens, 0),
        estimated_request_input_tokens_total = estimated_request_input_tokens_total + COALESCE(NEW.estimated_request_input_tokens, 0)
      WHERE id = NEW.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_delete_update_batch_counters
    AFTER DELETE ON requests
    BEGIN
      UPDATE batches
      SET
        request_count = request_count - 1,
        size_bytes = size_bytes - COALESCE(OLD.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total - COALESCE(OLD.estimated_input_tokens, 0),
        estimated_request_input_tokens_total = estimated_request_input_tokens_total - COALESCE(OLD.estimated_request_input_tokens, 0)
      WHERE id = OLD.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_update_same_batch_update_counters
    AFTER UPDATE OF request_payload_size, estimated_input_tokens, estimated_request_input_tokens ON requests
    WHEN OLD.batch_id = NEW.batch_id
    BEGIN
      UPDATE batches
      SET
        size_bytes = size_bytes + (COALESCE(NEW.request_payload_size, 0) - COALESCE(OLD.request_payload_size, 0)),
        estimated_input_tokens_total = estimated_input_tokens_total + (COALESCE(NEW.estimated_input_tokens, 0) - COALESCE(OLD.estimated_input_tokens, 0)),
        estimated_request_input_tokens_total = estimated_request_input_tokens_total + (COALESCE(NEW.estimated_request_input_tokens, 0) - COALESCE(OLD.estimated_request_input_tokens, 0))
      WHERE id = NEW.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_update_move_batch_update_counters
    AFTER UPDATE OF batch_id, request_payload_size, estimated_input_tokens, estimated_request_input_tokens ON requests
    WHEN OLD.batch_id != NEW.batch_id
    BEGIN
      UPDATE batches
      SET
        request_count = request_count - 1,
        size_bytes = size_bytes - COALESCE(OLD.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total - COALESCE(OLD.estimated_input_tokens, 0),
        estimated_request_input_tokens_total = estimated_request_input_tokens_total - COALESCE(OLD.estimated_request_input_tokens, 0)
      WHERE id = OLD.batch_id;

      UPDATE batches
      SET
        request_count = request_count + 1,
        size_bytes = size_bytes + COALESCE(NEW.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total + COALESCE(NEW.estimated_input_tokens, 0),
        estimated_request_input_tokens_total = estimated_request_input_tokens_total + COALESCE(NEW.estimated_request_input_tokens, 0)
      WHERE id = NEW.batch_id;
    END;
    """)
  end

  def down do
    execute("""
    DROP TRIGGER IF EXISTS requests_after_update_move_batch_update_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_update_same_batch_update_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_delete_update_batch_counters;
    """)

    execute("""
    DROP TRIGGER IF EXISTS requests_after_insert_update_batch_counters;
    """)

    execute("""
    SELECT 1;
    """)

    alter table(:batches) do
      remove :estimated_request_input_tokens_total
    end

    alter table(:requests) do
      remove :estimated_request_input_tokens
    end

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_update_move_batch_update_counters
    AFTER UPDATE OF batch_id, request_payload_size, estimated_input_tokens ON requests
    WHEN OLD.batch_id != NEW.batch_id
    BEGIN
      UPDATE batches
      SET
        request_count = request_count - 1,
        size_bytes = size_bytes - COALESCE(OLD.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total - COALESCE(OLD.estimated_input_tokens, 0)
      WHERE id = OLD.batch_id;

      UPDATE batches
      SET
        request_count = request_count + 1,
        size_bytes = size_bytes + COALESCE(NEW.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total + COALESCE(NEW.estimated_input_tokens, 0)
      WHERE id = NEW.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_update_same_batch_update_counters
    AFTER UPDATE OF request_payload_size, estimated_input_tokens ON requests
    WHEN OLD.batch_id = NEW.batch_id
    BEGIN
      UPDATE batches
      SET
        size_bytes = size_bytes + (COALESCE(NEW.request_payload_size, 0) - COALESCE(OLD.request_payload_size, 0)),
        estimated_input_tokens_total = estimated_input_tokens_total + (COALESCE(NEW.estimated_input_tokens, 0) - COALESCE(OLD.estimated_input_tokens, 0))
      WHERE id = NEW.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_delete_update_batch_counters
    AFTER DELETE ON requests
    BEGIN
      UPDATE batches
      SET
        request_count = request_count - 1,
        size_bytes = size_bytes - COALESCE(OLD.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total - COALESCE(OLD.estimated_input_tokens, 0)
      WHERE id = OLD.batch_id;
    END;
    """)

    execute("""
    CREATE TRIGGER IF NOT EXISTS requests_after_insert_update_batch_counters
    AFTER INSERT ON requests
    BEGIN
      UPDATE batches
      SET
        request_count = request_count + 1,
        size_bytes = size_bytes + COALESCE(NEW.request_payload_size, 0),
        estimated_input_tokens_total = estimated_input_tokens_total + COALESCE(NEW.estimated_input_tokens, 0)
      WHERE id = NEW.batch_id;
    END;
    """)

    execute("""
    UPDATE batches
    SET
      request_count = (
        SELECT COUNT(*)
        FROM requests
        WHERE requests.batch_id = batches.id
      ),
      estimated_input_tokens_total = COALESCE((
        SELECT SUM(estimated_input_tokens)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0),
      size_bytes = COALESCE((
        SELECT SUM(request_payload_size)
        FROM requests
        WHERE requests.batch_id = batches.id
      ), 0)
    """)
  end
end
