defmodule Batcher.Repo.Migrations.RemoveRequestDeliveryAttemptCountCalcOnly do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:requests) do
      remove_if_exists :delivery_attempt_count
    end
  end

  def down do
    alter table(:requests) do
      add :delivery_attempt_count, :bigint, null: false, default: 0
    end
  end
end
