defmodule Batcher.Repo.Migrations.AddExpiresAtToBatch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:batches) do
      add :expires_at, :utc_datetime
    end
  end

  def down do
    alter table(:batches) do
      remove :expires_at
    end
  end
end
