defmodule Batcher.Repo.Migrations.MakeCustomIdGloballyUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:requests, ["custom_id", "batch_id"],
                     name: "requests_custom_id_batch_id_index"
                   )

    create index(:requests, ["custom_id"], unique: true)
  end

  def down do
    drop_if_exists index(:requests, ["custom_id"], name: "requests_custom_id_index")

    create index(:requests, ["custom_id", "batch_id"], unique: true)
  end
end
