defmodule Batcher.Repo.Migrations.AddBatchDiagnostics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:batches) do
      add :last_submission_error, :text
      add :last_download_error, :text
    end
  end

  def down do
    alter table(:batches) do
      remove :last_download_error
      remove :last_submission_error
    end
  end
end
