defmodule Batcher.Repo.Migrations.SyncRequestsPgTrgmStatementSplit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DROP INDEX IF EXISTS requests_custom_id_trgm_gin_index;
    """)

    execute("""
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    """)

    execute("""
    CREATE INDEX IF NOT EXISTS requests_custom_id_trgm_gin_index
    ON requests USING gin (custom_id gin_trgm_ops);
    """)
  end

  def down do
    execute("DROP INDEX IF EXISTS requests_custom_id_trgm_gin_index;")

    execute("SELECT 1;")

    execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    execute("""
    CREATE INDEX IF NOT EXISTS requests_custom_id_trgm_gin_index
    ON requests USING gin (custom_id gin_trgm_ops);
    """)
  end
end
