defmodule Batcher.Repo.Migrations.OpenaiRequestProgressTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:batches) do
      add :openai_requests_completed, :bigint
      add :openai_requests_failed, :bigint
      add :openai_requests_total, :bigint
    end
  end

  def down do
    alter table(:batches) do
      remove :openai_requests_total
      remove :openai_requests_failed
      remove :openai_requests_completed
    end
  end
end
