defmodule Batcher.Repo.Migrations.TokenLimitRetryBackoffV2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:batches) do
      add :token_limit_retry_attempts, :bigint, default: 0
      add :token_limit_retry_next_at, :utc_datetime
      add :token_limit_retry_last_error, :text
    end
  end

  def down do
    alter table(:batches) do
      remove :token_limit_retry_last_error
      remove :token_limit_retry_next_at
      remove :token_limit_retry_attempts
    end
  end
end
