defmodule Batcher.Repo.Migrations.AddSubmissionErrorCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:batches) do
      add :last_submission_error_code, :text
    end
  end

  def down do
    alter table(:batches) do
      remove :last_submission_error_code
    end
  end
end
